### ISSUE TITLE
Explicitly set byte order in new

### ISSUE THREAD

**Issue by sturfee-petrl** [zhuangsirui/binpacker#8]
I spent all day to find this problem :disappointed:. It was absolutely not obvious.
https://github.com/zhuangsirui/binpacker/commit/f1b53c477754cc3d873952fd6bc1b759aa01a464#commitcomment-24315680

Byte order is only one important option when you need work with binary. There are sense to add it directly to signature.

I propose explicitly add byte order to new functions. **It's go way. It should be obvious.**

```go
func NewPacker(writer io.Writer, byteOrder binary.ByteOrder) *Packer{}

func NewUnpacker(reader io.Reader, byteOrder binary.ByteOrder) *Unpacker{}
```

I thought about _NewPackerWithOrder_ but it's not good idea. binpacker single purpose package and it should be **concise**. _SetByteOrder_ would be unused.

:warning:**Comparability is broken.** :warning: **At least people will see immediately compilation error.**

**Comment by im7mortal** [comment]
Compatibility instead comparability :grin:

**Comment by zhuangsirui** [comment]
Thanks for your advise. But I think use [Semantic Versioning](http://semver.org/) to handle this situation is a better idea.

**Comment by zhuangsirui** [comment]
@sturfee-petrl @im7mortal So sorry for this issue. I will use Semantic Versioning later.

**Comment by im7mortal** [comment]
I want to reassure you one more time.

There are only 2 options **LittleEndian** or **BigEndian**. 
It's much more clear to set it in *New*. Then do redundant _SetByteOrder_. 
There are no more important parameters for _ thebinpacker_. 

Like I told before :point_right: **go way is when code is ridiculously simple** :point_left:. There no any clearance why it have LittleEndian by default. **It's black box.** :collision:

There a lot of examples when _New_ function have important explicit parameters in standard library.
For example *encoding/base32*
```
    func NewDecoder(enc *Encoding, r io.Reader) io.Reader
    func NewEncoder(enc *Encoding, w io.Writer) io.WriteCloser
```
:warning: You can notice that Encoding even first parameter! :warning: Because it's important to tell people what they are going to do!! :exclamation:

**LittleEndian** and **BigEndian** are also encoding
People should first choose encoding. Nobody forgot about Reader or Writer. But everyone forgot about _SetByteOrder_.  :100:

**Comment by zhuangsirui** [comment]
@im7mortal I'm think about this again and I think your idea is the correct solution. I'm a little busy these days, can you send a PR for this please?
